#include <iostream.h>
#include <conio.h>

main()
{
int yoga [2][3];
cout<<"Bilangan 1 = ";
cin>>yoga[0][0];
cout<<"Bilangan 2 = ";
cin>>yoga[0][1];
cout<<"Bilangan 3 = ";
cin>>yoga[0][2];
cout<<"Bilangan 4 = ";
cin>>yoga[1][0];
cout<<"Bilangan 5 = ";
cin>>yoga[1][1];
cout<<"Bilangan 6 = ";
cin>>yoga[1][2];

cout<<"hasil ="<<yoga[0][0]+yoga[0][1]+yoga[0][2]+yoga[1][0]+yoga[1][1]+yoga[1][2]<<endl;

getch();
}
